SELECT ADDR_LINK.PART_ID,
          ADDR_LINK.ADD_ID,
          ADDR_LINK.ADDR_TYPE,
          ADDR_CORE.VERSION,
          ADDR_CORE.EVENT_DATE,
          ADDR_CORE.USERID,
          ADDR_CORE.ADDRESS_LINE1,
          ADDR_CORE.FROM_DATE,
          ADDR_CORE.POSTCODE,
          ADDR_CORE.COUNTRY_CODE,
          ADDR_CORE.ADDRESS_LINE2,
          ADDR_CORE.ADDRESS_LINE3,
          ADDR_EXT.CITY,
          ADDR_EXT.STATE,
          ADDR_EXT.PHONE_CODE,
          ADDR_EXT.PHONE_NO,
          ADDR_EXT.FAX1_CODE,
          ADDR_EXT.FAX1_NO,
          ADDR_EXT.FAX2_CODE,
          ADDR_EXT.FAX2_NO,
          ADDR_LINK.ADD_CODE,
          ADDR_LINK.DEFAULT_ADDR,
          ADDR_EXT.LATITUDE,
          ADDR_EXT.LONGITUDE,
          ADDR_EXT.PLUS_CODE,
          ADDR_EXT.PLACE_ID,
          ADDR_EXT.UNIT_NO,
          ADDR_EXT.TEMP_ADDRESS_LINE1
     FROM CPGE_ADDRESSES_LINK addr_link,
          cp_v_addresses addr_core,
          CPGE_ADDRESSES addr_ext
    WHERE     addr_link.add_id = addr_core.add_id
          AND addr_core.add_id = addr_ext.add_id